services:
  registry:
    image: registry:3
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge