services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
      - /lib/modules:/lib/modules
    command: ["/bin/bash", "/etc/wireguard/entrypoint.sh"]
    networks:
      vpn:
        ipv4_address: 10.10.0.1

  vault:
    image: hashicorp/vault:1.20
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: /vault/config/config.hcl
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data:/vault/file
    networks:
      vpn:
        ipv4_address: 10.10.0.2

  registry:
    image: registry:3
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - registry_data:/var/lib/registry
    networks:
      vpn:
        ipv4_address: 10.10.0.3

volumes:
  vault_data:
  registry_data:

networks:
  vpn:
    ipam:
      config:
        - subnet: 10.10.0.0/24