services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard-intranet
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil/West # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      #- SERVERURL=<your-server-url> #optional
      #- SERVERPORT=51820 #optional
      #- PEERS=1 #optional
      #- PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf
      - /lib/modules:/lib/modules
    #command: ["/bin/bash", "/etc/wireguard/entrypoint.sh"]
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge
